version: '{build}'
build_script:
- cmd: build.cmd
test: off
environment:
  NuGetApiKey:
    secure: 31CPUTtZ2cHTln5cdemh2pM2gK355NZ/5467TFVSr5lFVxG0DOunPMrIuobgLpU9
artifacts:
- path: artifacts\**\*.*
